### ISSUE TITLE
error

### ISSUE THREAD

**Issue by OValery16** [DwangoMediaVillage/manga_frame_extraction#1]
Thank you for your amazing work. 

I have a problem to make it run. I have the following error.

In file included from /home/olivier/Desktop/manga_frame_extraction/MangaFrameExtraction/main.cpp:21:0:
/home/olivier/Desktop/manga_frame_extraction/MangaFrameExtraction/fsp.h: In member function ‘CvPoint FrameSeparation::calculate_ending_point(bool, int, int, int)’:
/home/olivier/Desktop/manga_frame_extraction/MangaFrameExtraction/fsp.h:145:86: error: no matching function for call to ‘CvPoint::CvPoint(int&, double)’
 _horizontal ? CvPoint(length, position + length * cos(to_rad(theta))) : CvPoint
                                                                     ^
In file included from /usr/local/include/opencv2/core/core_c.h:47:0,
                 from /usr/local/include/opencv2/opencv.hpp:46,
                 from /home/olivier/Desktop/manga_frame_extraction/MangaFrameExtraction/main.cpp:16:
/usr/local/include/opencv2/core/types_c.h:1021:16: note: candidate: CvPoint::CvPoint()
 typedef struct CvPoint
                ^
/usr/local/include/opencv2/core/types_c.h:1021:16: note:   candidate expects 0 arguments, 2 provided
/usr/local/include/opencv2/core/types_c.h:1021:16: note: candidate: constexpr CvPoint::CvPoint(const CvPoint&)
/usr/local/include/opencv2/core/types_c.h:1021:16: note:   candidate expects 1 argument, 2 provided
/usr/local/include/opencv2/core/types_c.h:1021:16: note: candidate: constexpr CvPoint::CvPoint(CvPoint&&)
/usr/local/include/opencv2/core/types_c.h:1021:16: note:   candidate expects 1 argument, 2 provided
In file included from /home/olivier/Desktop/manga_frame_extraction/MangaFrameExtraction/main.cpp:21:0:
/home/olivier/Desktop/manga_frame_extraction/MangaFrameExtraction/fsp.h:145:144: error: no matching function for call to ‘CvPoint::CvPoint(double, int&)’
  cos(to_rad(theta))) : CvPoint(position + length * cos(to_rad(theta)), length);
                                                                              ^
In file included from /usr/local/include/opencv2/core/core_c.h:47:0,
                 from /usr/local/include/opencv2/opencv.hpp:46,
                 from /home/olivier/Desktop/manga_frame_extraction/MangaFrameExtraction/main.cpp:16:
/usr/local/include/opencv2/core/types_c.h:1021:16: note: candidate: CvPoint::CvPoint()
 typedef struct CvPoint
                ^
/usr/local/include/opencv2/core/types_c.h:1021:16: note:   candidate expects 0 arguments, 2 provided
/usr/local/include/opencv2/core/types_c.h:1021:16: note: candidate: constexpr CvPoint::CvPoint(const CvPoint&)
/usr/local/include/opencv2/core/types_c.h:1021:16: note:   candidate expects 1 argument, 2 provided
/usr/local/include/opencv2/core/types_c.h:1021:16: note: candidate: constexpr CvPoint::CvPoint(CvPoint&&)
/usr/local/include/opencv2/core/types_c.h:1021:16: note:   candidate expects 1 argument, 2 provided
CMakeFiles/MFE.dir/build.make:62: recipe for target 'CMakeFiles/MFE.dir/main.cpp.o' failed
make[2]: *** [CMakeFiles/MFE.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/MFE.dir/all' failed
make[1]: *** [CMakeFiles/MFE.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Hiroshiba** [comment]
Thank you for reporting!
We forgot to write that we need opencv3 to build our code.
I will write it in the README!
